### ISSUE TITLE
Supporting internal 8bit encoding for XYZ color space

### ISSUE THREAD

**Issue by ktsc** [InternationalColorConsortium/RefIccMAX#13]
In `IccCmm.cpp`, inside the methods `CIccCmm::ToInternalEncoding` (line `8045`) and `CIccCmm::FromInternalEncoding` (line `8354`), an encoding of 8 bits while using the XYZ color space is currently not implemented, I was wondering whether this encoding is possible with the XYZ space or not?
Thanks

**Comment by beku** [comment]
CIE\*XYZ with 8-bit precision make usually no sense, as the **banding artifacts** are extreme because of the **linear gamma** encoding in CIE\*XYZ.

**Comment by maxderhak** [comment]
There is no 8-bit encoding specified by the ICC specifications for the reason Kai-Uwe mentioned.  Thus RefIccMAX doesn't support 8-bit XYZ.
