### ISSUE TITLE
What kind of data that I need to prepare for creating an Icc Profile?

### ISSUE THREAD

**Issue by ghost** [InternationalColorConsortium/RefIccMAX#14]
I'm a newcomer in Icc profile.

I saw a lot of examples in IccProfLib and RefIccMax, but I still no any ideas to create an Icc profile.
I have a big problem that what kind of data for creating an Icc Profile.
All examples are compiled success, but I don't know how to use it. because I don't known how to prepare data for input.
for example: create_CLUT_profile command tool

Could you give me some advice?
thanks

**Comment by maxderhak** [comment]
RefIccMAX is a low level library that provides the ability to interact with the iccMAX profile format.  However, it doesn't have the logic to go from measurement data to a profile that can be used in an application.
