### ISSUE TITLE
Library names

### ISSUE THREAD

**Issue by beku** [InternationalColorConsortium/RefIccMAX#17]
It might be worthwhile to consider related library names, as the two previous projects moved into a single on.

SampleICC (past): libSampleICC.a
IccXML (past): libIccXML.a
IccProfLib (now): *lib*IccProf*Lib*.a

proposed:
IccProfLib: lib*RefIccMax*Prof.a
IccXML: lib*RefIccMax*Xml.a

other ideas welcome

**Comment by maxderhak** [comment]
I think of these as a logical successors (essentially the next major version).

How about:
IccProLIb:  libIccProfLib2.a
IccXML: libIccXML2.a

**Comment by beku** [comment]
Create two branchs (**libIccProfLib2** and **libIccProf2**), which you could choose to merge.

Both branches change library names and append at least the major version number 2.
Both branches change as well the include prefixes.

**Comment by maxderhak** [comment]
Can you elaborate further?

**Comment by beku** [comment]
I've created two pull requests, which you can pick one.

**Comment by beku** [comment]
selected #19
