### ISSUE TITLE
Does it possible to create CMYK output icc profile using this SDK?

### ISSUE THREAD

**Issue by diuming** [InternationalColorConsortium/RefIccMAX#23]
I'm a newbie with color technology and I'm interested in IccMax SDK.
I want to create a CMYK icc profile from some patches like IT8/7.4 CGATS.

These days I study Icc Profiles specifications `V2`, `V4`, `Color Management(Wiley)` and try to create an icc profile.
wow, it is a complex topic which involves a wide range of disciplines including computer science, numerical analysis, and colour science.

but I encountered some problems.
1)I don't know what data(format, values...) for APIs when I try to use these functions.
2)No any API document that I don't know how to start.
3)I can't find any examples for CMYK output icc profiling.

Q1)Do you have any plan to design CxF3 SDK for reading and writing?
Q2)Could you give me advice about creating CMYK output icc profile?

Thanks

**Comment by maxderhak** [comment]
The IccMAX SDK does not provide code to take measurements and create a profile from those measurements.  It is a low level library that makes it possible to for one to create a tool to that could take measurements and build a profile. As the iccMAX specification completes ISO standardization along with the development and adoption of Interoperability  Conformance Specifications such commercial tools will be forthcoming.
