### ISSUE TITLE
spectral white point naming mismatch

### ISSUE THREAD

**Issue by beku** [InternationalColorConsortium/RefIccMAX#29]
The examples contain 'smwp', like here:
https://github.com/InternationalColorConsortium/RefIccMAX/blob/master/Testing/Display/LCDDisplay.xml#L540
... translates maybe to Spectral Media White Point
The spec says in 9.2.106 spectralWhitePointTag
Tag signature: ‘swpt’ (73777074h)

Do I miss something? Which one is correct?

**Comment by maxderhak** [comment]
'swpt' is correct.  I believe the examples have been changes to reflect this as well.
