### ISSUE TITLE
Heap validation failure (MSVC Windows x64 Debug build) with fuzzing ICC

### ISSUE THREAD

**Issue by petervwyatt** [InternationalColorConsortium/RefIccMAX#40]
The attached ICC file (generated by fuzzing engine) generates a heap validation failure when doing "-v double-free.icc all" with iccDumpProfile on an MSVC-2019 Windows 10 x64 Debug build. We think it is a double-free. This was issue was identified using AFL-cmin fuzzing.

[double-free.zip](https://github.com/InternationalColorConsortium/RefIccMAX/files/5081885/double-free.zip)

**Comment by maxderhak** [comment]
Changes have been incorporated into code to address this

**Comment by petervwyatt** [comment]
I can still repro this on master for both MSVC-2019 Windows 10 x64 Debug and Release builds with the ICC in the attached ZIP:
![image](https://user-images.githubusercontent.com/26521615/104830455-5dcd2000-58d3-11eb-9227-8b82bf0e5e42.png)
