### ISSUE TITLE
Replace Windows & OS X specific projects with CMake

### ISSUE THREAD

**Issue by dwightkelly** [InternationalColorConsortium/RefIccMAX#6]
Instead of maintaining separate platform specific projects, create a single CMake

**Comment by maxderhak** [comment]
I'm open to the possibility of someone submitting the work.

**Comment by beku** [comment]
XCode build options:
- cmake: works fine, both with the cmake -G Xcode option and with default Unix Makefiles generator
  - Covered are libxml2 on OS X 10.10, it is detected and used
  - libtiff needs to be build externally for the Tiff tools
  - Still need to find out how the cmake generated project can be distributed.
- BuildAll.sh - needs to be tested
- several XCode projects in each source path
  - make they still sense?
  - Can they be removed after the migration to cmake's XCode project, e.g. after CMM integration

**Comment by beku** [comment]
Update:
- all XCode projects are used
  - SDKROOT is fixed in https://github.com/InternationalColorConsortium/RefIccMAX/commit/ea0e45d219fbf4ec380f4427138ff0422b69c57e
- BuildAll.sh is used to build the several predefined XCode projects in one batch

**Comment by beku** [comment]
Cmake - Xcode integration has some issues:
1. **Rewrite:** In case of a update in the CMakeLists.txt files, the XCode project needs to be updated. The XCode project is rewritten during the update.
2. **Absolute Paths:** paths in the generated XCode project are absolute. The resulting project file can not be redistributed in that form.
3. **Clutter:** the generated Xcode project directory is filled with some cmake specific files, which looks not nice. Here is the listing (*RefIccMAX.xcodeproj* contains the XCode project):
*CMakeCache.txt
CMakeFiles/
cmake_install.cmake
CMakeScripts/
IccProfLib/
IccXML/
RefIccMAX.build/
RefIccMAXConfig.cmake
RefIccMAXUninstall.cmake
RefIccMAX.xcodeproj/
Testing/
Tools/*
Among these files are some, which need to be distributed for a functional XCode project.

The path of generating a relocatable XCode project from CMake looks not easily maintainable. On the other side, the time needed to fix the existing XCode projects was moderate.

That said, the generated XCode project is useable on a single computer and worked as expected. But it needs a additional cmake installation.
